spring:
  application:
    name: temperature-anomaly-detector
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ${spring.application.name}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.always.right.inc.temperature_anomaly_detector
        spring.json.type.mapping: >
          temperature-measurement:com.always.right.inc.temperature_anomaly_detector.adapter.inbound.kafka.TemperatureMeasurementEvent,
          temperature-anomaly-detected:com.always.right.inc.temperature_anomaly_detector.service.TemperatureAnomalyDetectedEvent
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: temperature-anomaly-detected:com.always.right.inc.temperature_anomaly_detector.service.TemperatureAnomalyDetectedEvent
    listener:
      observation-enabled: true
  mongodb:
    # Of course this should be taken from secrets
    uri: mongodb://admin:secret@localhost:27017/temperature_anomaly_detector?authSource=admin
    representation:
      uuid: standard

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  tracing:
    sampling:
      probability: 1.0
  prometheus:
    metrics:
      export:
        enabled: true
anomaly-detection:
  type: consecutive
  threshold: 5.0
  window-size: 10
